Feat/controller implementation
dev-sys-do/sealci pull request #14
Opened 2024-07-19 10:03 UTC by Courtcircuits

Implementation of the controller

2024-08-17 07:25 UTC, sameo commented on .idea/.gitignore
Please remove all `.idea`files.

2024-08-30 15:15 UTC, hugoponthieu requested changes
I was wondering if adding route for fetching a stream that expose the state of the pipeline was possible

2024-08-30 15:15 UTC, hugoponthieu commented on controller/src/action/action_repository.rs
> +    container_uri: String,
What is container_uri ?

2024-08-30 18:04 UTC, theotchlx requested changes
Hi, thank you for this great work and PR.

I suggested below some adjustments and questions

2024-08-30 18:04 UTC, theotchlx commented on docs/arch/lexicon.md
> -
Please re-add this removed empty line at the end of this .md file

No blank lines at the end of a file is not up to markdown standards,

And generally, it is best to leave one blank line at the end of any file (source code included), as many older tools won't work properly if a line feed isn't present. Also it is a POSIX standard, as it is the definition of a line: https://pubs.opengroup.org/onlinepubs/9699919799/basedefs/V1_chap03.html#tag_03_206

2024-08-31 13:36 UTC, Courtcircuits commented on controller/src/scheduler/mod.rs
> +}
You can put code inside `mod.rs`. E.g : https://github.com/tokio-rs/axum/blob/main/axum/src/response/mod.rs

2024-08-31 13:37 UTC, Courtcircuits commented on controller/src/pipeline/pipeline_service.rs
> +        // }
Nope we will get rid of it

2024-08-31 13:37 UTC, Courtcircuits commented on controller/src/pipeline/pipeline_controller.rs
> +        Err(err) => HttpResponse::BadRequest().body(format!("{:?}", err)), //TODO: replace this by exhaustive match
Yes

2024-08-31 13:37 UTC, Courtcircuits commented on controller/.gitignore
We'll do it

2024-09-11 11:57 UTC, hugoponthieu approved these changes
The code is clean, consider merging this part

2024-09-11 12:01 UTC, Courtcircuits commented
> The code is clean, consider merging this part

We still need to separate the "commands" into a dedicated repository. This is in progress, so until it's committed I would rather not merge this branch. Sorry for the wait

2024-09-22 17:03 UTC, merged